//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR_Reader
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code_history
    {
        public int Id { get; set; }
        public Nullable<int> Brand_Id { get; set; }
        public Nullable<int> Reader_Id { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
    
        public virtual Reader Reader { get; set; }
        public virtual Brand_Code Brand_Code { get; set; }
    }
}
